# Generated by Django 3.2 on 2022-02-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_order_discount_available',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
