# Generated by Django 3.2 on 2022-02-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_first_order_discount_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_order_discount_available',
        ),
    ]
